CHATBOT_TRAINING_DATA = [
    # Greetings & Basic (50)
    ("hello", "greeting"),
    ("hi", "greeting"),
    ("good morning", "greeting"),
    ("good afternoon", "greeting"),
    ("hey", "greeting"),
    ("hello there", "greeting"),
    ("hi there", "greeting"),
    ("good evening", "greeting"),
    ("morning", "greeting"),
    ("afternoon", "greeting"),
    ("evening", "greeting"),
    ("greetings", "greeting"),
    ("howdy", "greeting"),
    ("yo", "greeting"),
    ("what's up", "greeting"),
    ("hello system", "greeting"),
    ("hi bot", "greeting"),
    ("hello assistant", "greeting"),
    ("hi assistant", "greeting"),
    ("hey there", "greeting"),
    ("good day", "greeting"),
    ("hello erp", "greeting"),
    ("hi erp", "greeting"),
    ("hey erp", "greeting"),
    ("hello erpnext", "greeting"),
    ("hi erpnext", "greeting"),
    ("hey erpnext", "greeting"),
    ("hello business system", "greeting"),
    ("hi business system", "greeting"),
    ("hey business system", "greeting"),
    ("hello accounting system", "greeting"),
    ("hi accounting system", "greeting"),
    ("hey accounting system", "greeting"),
    ("hello management system", "greeting"),
    ("hi management system", "greeting"),
    ("hey management system", "greeting"),
    ("hello enterprise system", "greeting"),
    ("hi enterprise system", "greeting"),
    ("hey enterprise system", "greeting"),
    ("hello company system", "greeting"),
    ("hi company system", "greeting"),
    ("hey company system", "greeting"),
    ("hello organization system", "greeting"),
    ("hi organization system", "greeting"),
    ("hey organization system", "greeting"),
    ("hello team", "greeting"),
    ("hi team", "greeting"),
    ("hey team", "greeting"),
    ("hello everyone", "greeting"),
    ("hi everyone", "greeting"),

    # Help & Navigation (50)
    ("how do I create a sales invoice?", "help_request"),
    ("where can I find customer records?", "help_request"),
    ("how to process a payment?", "help_request"),
    ("help with inventory management", "help_request"),
    ("how to generate financial reports?", "help_request"),
    ("where is the purchase module?", "help_request"),
    ("how to add new items?", "help_request"),
    ("help with accounting entries", "help_request"),
    ("how to set up taxes?", "help_request"),
    ("where are the HR settings?", "help_request"),
    ("how do I create a purchase order?", "help_request"),
    ("where can I view stock levels?", "help_request"),
    ("how to create a journal entry?", "help_request"),
    ("help with customer management", "help_request"),
    ("how to process payroll?", "help_request"),
    ("where is the manufacturing module?", "help_request"),
    ("how to create a project?", "help_request"),
    ("help with asset management", "help_request"),
    ("how to generate reports?", "help_request"),
    ("where are the system settings?", "help_request"),
    ("how do I create a lead?", "help_request"),
    ("where can I view invoices?", "help_request"),
    ("how to reconcile bank statements?", "help_request"),
    ("help with quality management", "help_request"),
    ("how to create a work order?", "help_request"),
    ("where is the CRM module?", "help_request"),
    ("how to add new users?", "help_request"),
    ("help with expense claims", "help_request"),
    ("how to create a delivery note?", "help_request"),
    ("where can I view purchase orders?", "help_request"),
    ("how to update stock quantities?", "help_request"),
    ("help with leave applications", "help_request"),
    ("how to create a salary slip?", "help_request"),
    ("where is the asset module?", "help_request"),
    ("how to create a maintenance schedule?", "help_request"),
    ("help with website management", "help_request"),
    ("how to create a quotation?", "help_request"),
    ("where can I view trial balance?", "help_request"),
    ("how to create a credit note?", "help_request"),
    ("help with supplier management", "help_request"),
    ("how to create a sales order?", "help_request"),
    ("where is the reporting module?", "help_request"),
    ("how to create a payment entry?", "help_request"),
    ("help with production planning", "help_request"),
    ("how to create a timesheet?", "help_request"),
    ("where can I view balance sheet?", "help_request"),
    ("how to create a stock entry?", "help_request"),
    ("help with employee management", "help_request"),
    ("how to create a material request?", "help_request"),
    ("where is the support module?", "help_request"),

    # Sales & Invoices (50)
    ("create new sales invoice", "sales_invoice"),
    ("show pending invoices", "sales_invoice"),
    ("view invoice INV-2023-001", "sales_invoice"),
    ("check invoice status for customer ABC Corp", "sales_invoice"),
    ("download invoice PDF", "sales_invoice"),
    ("email invoice to customer", "sales_invoice"),
    ("mark invoice as paid", "sales_invoice"),
    ("cancel sales invoice", "sales_invoice"),
    ("view sales return", "sales_invoice"),
    ("generate proforma invoice", "sales_invoice"),
    ("create sales invoice with multiple payment terms", "sales_invoice"),
    ("apply discount to invoice line items", "sales_invoice"),
    ("allocate advance payment against invoice", "sales_invoice"),
    ("create recurring sales invoice", "sales_invoice"),
    ("update shipping rule for invoice", "sales_invoice"),
    ("apply rounding adjustment in invoice", "sales_invoice"),
    ("create debit note for customer", "sales_invoice"),
    ("view invoice wise payment details", "sales_invoice"),
    ("export invoice data to JSON", "sales_invoice"),
    ("create sales invoice with taxes and charges", "sales_invoice"),
    ("create delivery note for sales order SO-001", "sales_invoice"),
    ("post sales invoice against delivery note", "sales_invoice"),
    ("create credit note for returned goods", "sales_invoice"),
    ("create opening invoice for new customer", "sales_invoice"),
    ("create sales order from quotation", "sales_invoice"),
    ("update delivery date for sales order", "sales_invoice"),
    ("create packing slip", "sales_invoice"),
    ("update shipping address for order", "sales_invoice"),
    ("create installment payment plan", "sales_invoice"),
    ("create invoice in foreign currency", "sales_invoice"),
    ("create order entry", "sales_invoice"),
    ("update package details", "sales_invoice"),
    ("create delivery stop", "sales_invoice"),
    ("update shipping label", "sales_invoice"),
    ("create sales invoice with service items", "sales_invoice"),
    ("process sales return with replacement", "sales_invoice"),
    ("create invoice with consignment stock", "sales_invoice"),
    ("update invoice payment terms", "sales_invoice"),
    ("create sales invoice with project link", "sales_invoice"),
    ("process bulk invoice generation", "sales_invoice"),
    ("create sales invoice with batch items", "sales_invoice"),
    ("update invoice discount percentage", "sales_invoice"),
    ("create sales invoice with serialized items", "sales_invoice"),
    ("process invoice cancellation with credit note", "sales_invoice"),
    ("create sales invoice with asset items", "sales_invoice"),
    ("update invoice due date", "sales_invoice"),
    ("create sales invoice with multiple warehouses", "sales_invoice"),
    ("process partial invoice payment", "sales_invoice"),
    ("create sales invoice with landed costs", "sales_invoice"),
    ("update invoice billing cycle", "sales_invoice"),

    # Purchase & Bills (50)
    ("create purchase order", "purchase_order"),
    ("view vendor bills", "purchase_order"),
    ("check PO status PO-2023-001", "purchase_order"),
    ("approve purchase invoice", "purchase_order"),
    ("match GRN with purchase invoice", "purchase_order"),
    ("view pending payments to vendors", "purchase_order"),
    ("create purchase invoice with landed costs", "purchase_order"),
    ("apply retention money on purchase invoice", "purchase_order"),
    ("create purchase invoice with asset items", "purchase_order"),
    ("process purchase return against supplier", "purchase_order"),
    ("create purchase order with multiple warehouses", "purchase_order"),
    ("update billing address for supplier invoice", "purchase_order"),
    ("match purchase receipt with multiple invoices", "purchase_order"),
    ("create purchase invoice with service items", "purchase_order"),
    ("apply TDS on purchase invoice", "purchase_order"),
    ("create purchase order with scheduled dates", "purchase_order"),
    ("create payment request for supplier", "purchase_order"),
    ("create supplier quotation", "purchase_order"),
    ("convert supplier quotation to purchase order", "purchase_order"),
    ("create purchase receipt", "purchase_order"),
    ("match purchase receipt with invoice", "purchase_order"),
    ("create purchase order with quality inspection", "purchase_order"),
    ("update purchase order delivery schedule", "purchase_order"),
    ("create purchase invoice with advance payment", "purchase_order"),
    ("process purchase return with debit note", "purchase_order"),
    ("create purchase order from material request", "purchase_order"),
    ("update purchase order terms and conditions", "purchase_order"),
    ("create purchase invoice with exchange rate difference", "purchase_order"),
    ("process bulk purchase order creation", "purchase_order"),
    ("create purchase order with subcontracting", "purchase_order"),
    ("update purchase invoice payment status", "purchase_order"),
    ("create purchase order with consignment", "purchase_order"),
    ("process purchase invoice with quality rejection", "purchase_order"),
    ("create purchase order with batch items", "purchase_order"),
    ("update purchase order approval workflow", "purchase_order"),
    ("create purchase invoice with freight charges", "purchase_order"),
    ("process purchase order amendment", "purchase_order"),
    ("create purchase order with serialized items", "purchase_order"),
    ("update purchase invoice tax calculations", "purchase_order"),
    ("create purchase order with project link", "purchase_order"),
    ("process purchase return with replacement", "purchase_order"),
    ("create purchase invoice with installation charges", "purchase_order"),
    ("update purchase order validity period", "purchase_order"),
    ("create purchase order with maintenance contract", "purchase_order"),
    ("process purchase invoice with warranty details", "purchase_order"),
    ("create purchase order with insurance coverage", "purchase_order"),
    ("update purchase invoice discount terms", "purchase_order"),
    ("create purchase order with delivery instructions", "purchase_order"),
    ("process purchase invoice with bank charges", "purchase_order"),
    ("create purchase order with inspection criteria", "purchase_order"),

    # Inventory & Stock (50)
    ("check stock levels for item ABC-123", "inventory_query"),
    ("show low stock items", "inventory_query"),
    ("update stock quantity", "inventory_query"),
    ("create stock entry", "inventory_query"),
    ("view stock ledger", "inventory_query"),
    ("check batch details", "inventory_query"),
    ("serial number status for S/N-001", "inventory_query"),
    ("create material receipt", "inventory_query"),
    ("process material issue", "inventory_query"),
    ("view warehouse transfers", "inventory_query"),
    ("update item valuation using FIFO", "inventory_query"),
    ("create stock reconciliation for specific warehouse", "inventory_query"),
    ("process stock transfer with serial numbers", "inventory_query"),
    ("update batch expiry dates", "inventory_query"),
    ("create subcontracted item stock entry", "inventory_query"),
    ("process manufacturing stock entry", "inventory_query"),
    ("create material consumption entry", "inventory_query"),
    ("update item reorder level", "inventory_query"),
    ("create scrap material entry", "inventory_query"),
    ("process item repacking entry", "inventory_query"),
    ("update item price in price list", "inventory_query"),
    ("check item valuation rate", "inventory_query"),
    ("create stock reconciliation", "inventory_query"),
    ("process stock transfer between warehouses", "inventory_query"),
    ("create material request for production", "inventory_query"),
    ("create website item with description", "inventory_query"),
    ("update multi-currency pricing", "inventory_query"),
    ("create restaurant menu", "inventory_query"),
    ("update ingredient details", "inventory_query"),
    ("create service item with rates", "inventory_query"),
    ("update spare parts details", "inventory_query"),
    ("create property details", "inventory_query"),
    ("update crop details", "inventory_query"),
    ("update medication details", "inventory_query"),
    ("update fertilizer details", "inventory_query"),
    ("create stock entry for quality inspection", "inventory_query"),
    ("update item shelf life", "inventory_query"),
    ("create stock entry for sample items", "inventory_query"),
    ("update item storage conditions", "inventory_query"),
    ("create stock entry for demonstration items", "inventory_query"),
    ("update item minimum order quantity", "inventory_query"),
    ("create stock entry for exhibition items", "inventory_query"),
    ("update item safety stock level", "inventory_query"),
    ("create stock entry for testing items", "inventory_query"),
    ("update item lead time", "inventory_query"),
    ("create stock entry for donation items", "inventory_query"),
    ("update item packaging details", "inventory_query"),
    ("create stock entry for promotional items", "inventory_query"),
    ("update item barcode details", "inventory_query"),
    ("create stock entry for replacement items", "inventory_query"),

    # CRM & Customers (50)
    ("add new customer", "crm_query"),
    ("view customer ABC Corp details", "crm_query"),
    ("update customer address", "crm_query"),
    ("create new lead", "crm_query"),
    ("convert lead to customer", "crm_query"),
    ("view customer credit limit", "crm_query"),
    ("check customer payment terms", "crm_query"),
    ("view sales history for customer", "crm_query"),
    ("create customer with multiple contacts", "crm_query"),
    ("update customer credit period", "crm_query"),
    ("create lead with source campaign", "crm_query"),
    ("assign customer to sales partner", "crm_query"),
    ("create opportunity with probability percentage", "crm_query"),
    ("update quotation with validity days", "crm_query"),
    ("create customer with multiple addresses", "crm_query"),
    ("update customer loyalty points", "crm_query"),
    ("create lead from website form", "crm_query"),
    ("assign opportunity to sales team", "crm_query"),
    ("create opportunity from lead", "crm_query"),
    ("update quotation status", "crm_query"),
    ("process credit limit update", "crm_query"),
    ("create territory for sales person", "crm_query"),
    ("assign customer to sales person", "crm_query"),
    ("create quality feedback from customer", "crm_query"),
    ("create product review moderation", "crm_query"),
    ("create patient appointment", "crm_query"),
    ("update patient vitals", "crm_query"),
    ("create patient encounter", "crm_query"),
    ("create insurance subscription", "crm_query"),
    ("create donor details", "crm_query"),
    ("update grant application", "crm_query"),
    ("update member details", "crm_query"),
    ("update campaign details", "crm_query"),
    ("create sponsorship details", "crm_query"),
    ("update table reservation", "crm_query"),
    ("update maintenance contract", "crm_query"),
    ("update rental contract", "crm_query"),
    ("update property inspection", "crm_query"),
    ("create lease agreement", "crm_query"),
    ("update tenant details", "crm_query"),
    ("update shipping address", "crm_query"),
    ("update tracking details", "crm_query"),
    ("create customer with foreign address", "crm_query"),
    ("create customer segmentation group", "crm_query"),
    ("update customer communication preferences", "crm_query"),
    ("create customer service ticket", "crm_query"),
    ("update customer satisfaction survey", "crm_query"),
    ("create customer referral program", "crm_query"),
    ("update customer account status", "crm_query"),
    ("create customer welcome email", "crm_query"),

    # Accounting & Finance (50)
    ("view general ledger", "accounting_query"),
    ("create journal entry", "accounting_query"),
    ("check trial balance", "accounting_query"),
    ("generate balance sheet", "accounting_query"),
    ("view profit and loss statement", "accounting_query"),
    ("reconcile bank statement", "accounting_query"),
    ("post depreciation entry", "accounting_query"),
    ("view tax collected", "accounting_query"),
    ("create payment entry with write off", "accounting_query"),
    ("process bank reconciliation with unreconciled entries", "accounting_query"),
    ("create journal entry for bank charges", "accounting_query"),
    ("post opening balance for customer", "accounting_query"),
    ("create payment entry with deducting tax", "accounting_query"),
    ("process interest calculation on overdue invoices", "accounting_query"),
    ("create journal entry for exchange gain/loss", "accounting_query"),
    ("post depreciation using straight line method", "accounting_query"),
    ("create payment term with credit days", "accounting_query"),
    ("process financial year closing entry", "accounting_query"),
    ("make payment entry for customer invoice", "accounting_query"),
    ("process bank reconciliation for June", "accounting_query"),
    ("match payment with invoice", "accounting_query"),
    ("create salary structure for new employee", "accounting_query"),
    ("process advance salary payment", "accounting_query"),
    ("create asset purchase entry", "accounting_query"),
    ("post depreciation for assets", "accounting_query"),
    ("create payment entry for supplier", "accounting_query"),
    ("create journal entry for adjustment", "accounting_query"),
    ("process partial payment", "accounting_query"),
    ("create fee structure", "accounting_query"),
    ("create fee schedule", "accounting_query"),
    ("create fund allocation", "accounting_query"),
    ("update maintenance charge", "accounting_query"),
    ("create agent commission", "accounting_query"),
    ("create freight charges", "accounting_query"),
    ("update exchange rate for currency", "accounting_query"),
    ("update currency exchange gain/loss", "accounting_query"),
    ("update TDS deduction details", "accounting_query"),
    ("create tax calculation sheet", "accounting_query"),
    ("create asset with depreciation details", "accounting_query"),
    ("update asset location and custodian", "accounting_query"),
    ("create asset movement entry", "accounting_query"),
    ("create asset depreciation entry", "accounting_query"),
    ("process asset disposal entry", "accounting_query"),
    ("update asset insurance details", "accounting_query"),
    ("create asset capitalization entry", "accounting_query"),
    ("process asset adjustment entry", "accounting_query"),
    ("create accounting period closing", "accounting_query"),
    ("update chart of accounts", "accounting_query"),
    ("create budget vs actual report", "accounting_query"),
    ("process intercompany transactions", "accounting_query"),

    # Projects & Tasks (50)
    ("create new project", "project_query"),
    ("assign task to team member", "project_query"),
    ("update task status", "project_query"),
    ("view project timeline", "project_query"),
    ("add timesheet entry", "project_query"),
    ("create project with tasks and milestones", "project_query"),
    ("update project with cost center", "project_query"),
    ("create timesheet with activity type", "project_query"),
    ("update project percentage completion automatically", "project_query"),
    ("create project with budget details", "project_query"),
    ("update task with dependencies", "project_query"),
    ("create project from sales order", "project_query"),
    ("update timesheet with billing hours", "project_query"),
    ("create project with customer details", "project_query"),
    ("update project status to completed", "project_query"),
    ("create timesheet for project", "project_query"),
    ("update project percentage completion", "project_query"),
    ("create crop cycle", "project_query"),
    ("update agriculture task", "project_query"),
    ("update course schedule", "project_query"),
    ("update program details", "project_query"),
    ("update service schedule", "project_query"),
    ("create installation details", "project_query"),
    ("create project with resource allocation", "project_query"),
    ("update project risk assessment", "project_query"),
    ("create project deliverable checklist", "project_query"),
    ("update project stakeholder details", "project_query"),
    ("create project communication plan", "project_query"),
    ("update project quality metrics", "project_query"),
    ("create project change request", "project_query"),
    ("update project document repository", "project_query"),
    ("create project lessons learned", "project_query"),
    ("update project budget allocation", "project_query"),
    ("create project status report", "project_query"),
    ("update project team availability", "project_query"),
    ("create project meeting minutes", "project_query"),
    ("update project equipment allocation", "project_query"),
    ("create project issue log", "project_query"),
    ("update project health indicators", "project_query"),
    ("create project closure report", "project_query"),
    ("update project success criteria", "project_query"),
    ("create project scope document", "project_query"),
    ("update project approval workflow", "project_query"),
    ("create project training plan", "project_query"),
    ("update project compliance checklist", "project_query"),
    ("create project vendor evaluation", "project_query"),
    ("update project performance metrics", "project_query"),
    ("create project handover document", "project_query"),
    ("update project maintenance schedule", "project_query"),
    ("create project warranty details", "project_query"),

    # Manufacturing (50)
    ("create work order", "manufacturing_query"),
    ("update production status", "manufacturing_query"),
    ("view BOM for product X", "manufacturing_query"),
    ("check raw material availability", "manufacturing_query"),
    ("process finished goods entry", "manufacturing_query"),
    ("create work order with operations", "manufacturing_query"),
    ("update BOM with operation details", "manufacturing_query"),
    ("create job card with time logs", "manufacturing_query"),
    ("process production plan with material requests", "manufacturing_query"),
    ("create BOM with sub-assemblies", "manufacturing_query"),
    ("update work order with actual times", "manufacturing_query"),
    ("create production plan based on sales orders", "manufacturing_query"),
    ("process quality inspection for finished goods", "manufacturing_query"),
    ("create work order with scrap items", "manufacturing_query"),
    ("update BOM with alternative items", "manufacturing_query"),
    ("create quality inspection", "manufacturing_query"),
    ("update job card status", "manufacturing_query"),
    ("update BOM cost", "manufacturing_query"),
    ("create quality inspection for purchase receipt", "manufacturing_query"),
    ("update quality inspection template", "manufacturing_query"),
    ("create quality inspection for delivery note", "manufacturing_query"),
    ("update quality inspection parameters", "manufacturing_query"),
    ("process quality action for non-conformance", "manufacturing_query"),
    ("update quality procedure document", "manufacturing_query"),
    ("process quality audit findings", "manufacturing_query"),
    ("create lab test template", "manufacturing_query"),
    ("update clinical procedure", "manufacturing_query"),
    ("create disease diagnosis", "manufacturing_query"),
    ("update food preparation details", "manufacturing_query"),
    ("update kitchen order ticket", "manufacturing_query"),
    ("create manufacturing process flow", "manufacturing_query"),
    ("update production line efficiency", "manufacturing_query"),
    ("create machine maintenance schedule", "manufacturing_query"),
    ("update production capacity planning", "manufacturing_query"),
    ("create quality control checklist", "manufacturing_query"),
    ("update production yield analysis", "manufacturing_query"),
    ("create manufacturing cost sheet", "manufacturing_query"),
    ("update production safety procedures", "manufacturing_query"),
    ("create batch production record", "manufacturing_query"),
    ("update manufacturing lead time", "manufacturing_query"),
    ("create production quality standards", "manufacturing_query"),
    ("update manufacturing waste management", "manufacturing_query"),
    ("create production training program", "manufacturing_query"),
    ("update manufacturing compliance documentation", "manufacturing_query"),
    ("create production innovation log", "manufacturing_query"),
    ("update manufacturing sustainability metrics", "manufacturing_query"),
    ("create production automation plan", "manufacturing_query"),
    ("update manufacturing risk assessment", "manufacturing_query"),
    ("create production continuous improvement", "manufacturing_query"),
    ("update manufacturing best practices", "manufacturing_query"),

    # HR & Payroll (50)
    ("create employee record", "hr_query"),
    ("apply for leave", "hr_query"),
    ("check attendance record", "hr_query"),
    ("view salary slip", "hr_query"),
    ("process payroll", "hr_query"),
    ("update employee information", "hr_query"),
    ("generate attendance report", "hr_query"),
    ("create employee with salary structure assignment", "hr_query"),
    ("process payroll for specific department", "hr_query"),
    ("create leave allocation for employee", "hr_query"),
    ("update attendance with overtime hours", "hr_query"),
    ("create salary slip with additional salary", "hr_query"),
    ("process employee loan repayment", "hr_query"),
    ("create employee advance payment", "hr_query"),
    ("update employee tax exemption declaration", "hr_query"),
    ("create appraisal for employee", "hr_query"),
    ("process full and final settlement", "hr_query"),
    ("create leave application", "hr_query"),
    ("process loan application", "hr_query"),
    ("create expense claim", "hr_query"),
    ("create student applicant", "hr_query"),
    ("update student attendance", "hr_query"),
    ("create program enrollment", "hr_query"),
    ("update assessment plan", "hr_query"),
    ("update student batch", "hr_query"),
    ("update instructor details", "hr_query"),
    ("update healthcare practitioner", "hr_query"),
    ("create volunteer details", "hr_query"),
    ("update certification details", "hr_query"),
    ("update waiter assignment", "hr_query"),
    ("create restaurant shift", "hr_query"),
    ("update technician details", "hr_query"),
    ("update driver details", "hr_query"),
    ("create employee onboarding checklist", "hr_query"),
    ("update employee performance review", "hr_query"),
    ("create training and development plan", "hr_query"),
    ("update employee benefits administration", "hr_query"),
    ("create HR policy documentation", "hr_query"),
    ("update employee engagement survey", "hr_query"),
    ("create recruitment process workflow", "hr_query"),
    ("update employee wellness program", "hr_query"),
    ("create succession planning document", "hr_query"),
    ("update employee recognition program", "hr_query"),
    ("create HR analytics dashboard", "hr_query"),
    ("update employee exit interview", "hr_query"),
    ("create talent management strategy", "hr_query"),
    ("update HR compliance checklist", "hr_query"),
    ("create workforce planning report", "hr_query"),
    ("update employee skills inventory", "hr_query"),
    ("create HR knowledge base", "hr_query"),

    # Support & Maintenance (50)
    ("raise support ticket", "support_query"),
    ("check ticket status", "support_query"),
    ("create maintenance schedule", "support_query"),
    ("log equipment issue", "support_query"),
    ("update asset maintenance schedule", "support_query"),
    ("create maintenance visit", "support_query"),
    ("log warranty claim", "support_query"),
    ("create asset repair entry", "support_query"),
    ("create warranty claim", "support_query"),
    ("update service level agreement", "settings_query"),
    ("create service call log", "support_query"),
    ("create quality review meeting", "project_query"),
    ("create quality goal for department", "hr_query"),
    ("update asset maintenance checklist", "support_query"),
    ("create preventive maintenance plan", "support_query"),
    ("update equipment calibration schedule", "support_query"),
    ("create facility maintenance request", "support_query"),
    ("update software update schedule", "support_query"),
    ("create IT support ticket", "support_query"),
    ("update network maintenance log", "support_query"),
    ("create hardware maintenance record", "support_query"),
    ("update database backup schedule", "support_query"),
    ("create security maintenance checklist", "support_query"),
    ("update system performance monitoring", "support_query"),
    ("create disaster recovery plan", "support_query"),
    ("update business continuity procedure", "support_query"),
    ("create customer support escalation", "support_query"),
    ("update technical support knowledge base", "support_query"),
    ("create remote support session", "support_query"),
    ("update onsite maintenance visit", "support_query"),
    ("create emergency maintenance request", "support_query"),
    ("update scheduled downtime notification", "support_query"),
    ("create maintenance team assignment", "support_query"),
    ("update spare parts inventory for maintenance", "support_query"),
    ("create maintenance cost tracking", "support_query"),
    ("update maintenance service contract", "support_query"),
    ("create equipment history log", "support_query"),
    ("update maintenance safety procedures", "support_query"),
    ("create maintenance quality check", "support_query"),
    ("update maintenance certification records", "support_query"),
    ("create maintenance training schedule", "support_query"),
    ("update maintenance compliance documentation", "support_query"),
    ("create maintenance performance metrics", "support_query"),
    ("update maintenance vendor evaluation", "support_query"),
    ("create maintenance budget tracking", "support_query"),
    ("update maintenance inventory management", "support_query"),
    ("create maintenance work order system", "support_query"),
    ("update maintenance priority matrix", "support_query"),
    ("create maintenance resource allocation", "support_query"),
    ("update maintenance documentation system", "support_query"),

    # Reports & Analytics (50)
    ("generate sales report", "report_query"),
    ("export data to Excel", "report_query"),
    ("view dashboard analytics", "report_query"),
    ("create custom report", "report_query"),
    ("schedule automated report", "report_query"),
    ("view aging report for receivables", "report_query"),
    ("generate stock summary report", "report_query"),
    ("generate stock aging report", "report_query"),
    ("create custom sales analytics dashboard", "report_query"),
    ("generate customer acquisition cost report", "report_query"),
    ("create employee productivity report", "report_query"),
    ("generate project profitability analysis", "report_query"),
    ("create supplier performance report", "report_query"),
    ("generate cash flow forecast", "report_query"),
    ("create inventory turnover report", "report_query"),
    ("generate customer churn analysis", "report_query"),
    ("create product profitability report", "report_query"),
    ("create audit trail report", "report_query"),
    ("create compliance certificate", "report_query"),
    ("create regulatory reporting", "report_query"),
    ("generate attendance analytics report", "report_query"),
    ("create production efficiency report", "report_query"),
    ("generate quality control statistics", "report_query"),
    ("create financial ratio analysis", "report_query"),
    ("generate market trend analysis", "report_query"),
    ("create competitor analysis report", "report_query"),
    ("generate risk assessment report", "report_query"),
    ("create sustainability metrics report", "report_query"),
    ("generate customer satisfaction report", "report_query"),
    ("create employee retention analysis", "report_query"),
    ("generate supply chain performance report", "report_query"),
    ("create energy consumption report", "report_query"),
    ("generate waste management report", "report_query"),
    ("create innovation metrics report", "report_query"),
    ("generate training effectiveness report", "report_query"),
    ("create health and safety report", "report_query"),
    ("generate compliance audit report", "report_query"),
    ("create technology adoption report", "report_query"),
    ("generate social responsibility report", "report_query"),
    ("create brand perception report", "report_query"),
    ("generate market share analysis", "report_query"),
    ("create product life cycle report", "report_query"),
    ("generate customer lifetime value report", "report_query"),
    ("create operational efficiency report", "report_query"),
    ("generate capital expenditure report", "report_query"),
    ("create research and development report", "report_query"),
    ("generate patent portfolio report", "report_query"),
    ("create intellectual property report", "report_query"),
    ("generate business continuity report", "report_query"),
    ("create disaster recovery report", "report_query"),

    # Settings & Configuration (50)
    ("add new user", "settings_query"),
    ("update company information", "settings_query"),
    ("configure email settings", "settings_query"),
    ("set up print format", "settings_query"),
    ("manage user permissions", "settings_query"),
    ("create payment terms template", "settings_query"),
    ("setup tax template for GST", "settings_query"),
    ("create print format for invoice", "settings_query"),
    ("update website slideshow", "settings_query"),
    ("create blog post on website", "settings_query"),
    ("update shopping cart settings", "settings_query"),
    ("create website theme customization", "settings_query"),
    ("update web form fields", "settings_query"),
    ("update website SEO settings", "settings_query"),
    ("create website popup message", "settings_query"),
    ("update payment gateway configuration", "settings_query"),
    ("create medical code", "settings_query"),
    ("update healthcare service unit", "settings_query"),
    ("update land unit details", "settings_query"),
    ("update soil texture details", "settings_query"),
    ("create weather data entry", "settings_query"),
    ("create chapter details", "settings_query"),
    ("create restaurant table", "settings_query"),
    ("create restaurant settings", "settings_query"),
    ("create property unit", "settings_query"),
    ("update amenity details", "settings_query"),
    ("create vehicle details", "settings_query"),
    ("create shipping rule with calculations", "settings_query"),
    ("update currency symbol settings", "settings_query"),
    ("create GST invoice format", "settings_query"),
    ("create compliance checklist", "settings_query"),
    ("update statutory requirements", "settings_query"),
    ("update data retention policy", "settings_query"),
    ("update legal entity details", "settings_query"),
    ("configure multi-company setup", "settings_query"),
    ("update fiscal year settings", "settings_query"),
    ("create custom field configuration", "settings_query"),
    ("update workflow rule settings", "settings_query"),
    ("configure auto-email notifications", "settings_query"),
    ("update system backup settings", "settings_query"),
    ("create role-based access control", "settings_query"),
    ("update database connection settings", "settings_query"),
    ("configure API integration settings", "settings_query"),
    ("update mobile app settings", "settings_query"),
    ("create data import templates", "settings_query"),
    ("update system performance settings", "settings_query"),
    ("configure security policy settings", "settings_query"),
    ("update audit trail settings", "settings_query"),
    ("create custom dashboard widgets", "settings_query"),
    ("update system localization settings", "settings_query"),

    # Thanks & Feedback (50)
    ("thank you", "thanks"),
    ("thanks for the help", "thanks"),
    ("appreciate it", "thanks"),
    ("thanks for your assistance", "thanks"),
    ("thank you very much", "thanks"),
    ("thanks a lot", "thanks"),
    ("much appreciated", "thanks"),
    ("thank you for your help", "thanks"),
    ("thanks for the information", "thanks"),
    ("appreciate your support", "thanks"),
    ("thank you for your time", "thanks"),
    ("thanks for your patience", "thanks"),
    ("thank you for explaining", "thanks"),
    ("thanks for clarifying", "thanks"),
    ("appreciate your guidance", "thanks"),
    ("thank you for the update", "thanks"),
    ("thanks for the quick response", "thanks"),
    ("thank you for your understanding", "thanks"),
    ("thanks for your cooperation", "thanks"),
    ("appreciate your professionalism", "thanks"),
    ("thank you for the solution", "thanks"),
    ("thanks for resolving the issue", "thanks"),
    ("thank you for your expertise", "thanks"),
    ("thanks for your attention", "thanks"),
    ("appreciate your efficiency", "thanks"),
    ("thank you for your dedication", "thanks"),
    ("thanks for your commitment", "thanks"),
    ("thank you for your hard work", "thanks"),
    ("thanks for going above and beyond", "thanks"),
    ("appreciate your thoroughness", "thanks"),
    ("thank you for your reliability", "thanks"),
    ("thanks for your consistency", "thanks"),
    ("thank you for your accuracy", "thanks"),
    ("thanks for your precision", "thanks"),
    ("appreciate your attention to detail", "thanks"),
    ("thank you for your promptness", "thanks"),
    ("thanks for your timeliness", "thanks"),
    ("thank you for your responsiveness", "thanks"),
    ("thanks for your availability", "thanks"),
    ("appreciate your accessibility", "thanks"),
    ("thank you for your flexibility", "thanks"),
    ("thanks for your adaptability", "thanks"),
    ("thank you for your innovation", "thanks"),
    ("thanks for your creativity", "thanks"),
    ("appreciate your problem-solving", "thanks"),
    ("thank you for your initiative", "thanks"),
    ("thanks for your proactiveness", "thanks"),
    ("thank you for your foresight", "thanks"),
    ("thanks for your strategic thinking", "thanks"),
    ("appreciate your business acumen", "thanks"),

    # Goodbye (50)
    ("bye", "goodbye"),
    ("goodbye", "goodbye"),
    ("see you", "goodbye"),
    ("goodbye for now", "goodbye"),
    ("see you later", "goodbye"),
    ("take care", "goodbye"),
    ("farewell", "goodbye"),
    ("good night", "goodbye"),
    ("have a good day", "goodbye"),
    ("have a nice day", "goodbye"),
    ("talk to you later", "goodbye"),
    ("catch you later", "goodbye"),
    ("until next time", "goodbye"),
    ("signing off", "goodbye"),
    ("logging off", "goodbye"),
    ("closing chat", "goodbye"),
    ("ending chat", "goodbye"),
    ("finishing chat", "goodbye"),
    ("completing chat", "goodbye"),
    ("done chatting", "goodbye"),
    ("finished chatting", "goodbye"),
    ("completed chatting", "goodbye"),
    ("ending conversation", "goodbye"),
    ("finishing conversation", "goodbye"),
    ("completing conversation", "goodbye"),
    ("done talking", "goodbye"),
    ("finished talking", "goodbye"),
    ("completed talking", "goodbye"),
    ("ending discussion", "goodbye"),
    ("finishing discussion", "goodbye"),
    ("completing discussion", "goodbye"),
    ("done discussing", "goodbye"),
    ("finished discussing", "goodbye"),
    ("completed discussing", "goodbye"),
    ("bye bye", "goodbye"),
    ("see ya", "goodbye"),
    ("take care now", "goodbye"),
    ("be well", "goodbye"),
    ("stay safe", "goodbye"),
    ("stay healthy", "goodbye"),
    ("stay happy", "goodbye"),
    ("stay productive", "goodbye"),
    ("stay efficient", "goodbye"),
    ("stay organized", "goodbye"),
    ("stay focused", "goodbye"),
    ("stay successful", "goodbye"),
    ("bye assistant", "goodbye"),
    ("goodbye assistant", "goodbye"),
    ("bye bot", "goodbye"),
    ("goodbye bot", "goodbye"),

    # Error & System (50)
    ("I got an error", "error_report"),
    ("system is slow", "error_report"),
    ("cannot save document", "error_report"),
    ("page not loading", "error_report"),
    ("error saving invoice", "error_report"),
    ("system crashed", "error_report"),
    ("database connection error", "error_report"),
    ("login failed", "error_report"),
    ("access denied", "error_report"),
    ("permission error", "error_report"),
    ("data not saving", "error_report"),
    ("file upload error", "error_report"),
    ("email sending failed", "error_report"),
    ("report generation error", "error_report"),
    ("print not working", "error_report"),
    ("export failed", "error_report"),
    ("import error", "error_report"),
    ("sync error", "error_report"),
    ("backup failed", "error_report"),
    ("restore error", "error_report"),
    ("update failed", "error_report"),
    ("installation error", "error_report"),
    ("configuration error", "error_report"),
    ("setup error", "error_report"),
    ("integration error", "error_report"),
    ("API connection error", "error_report"),
    ("payment gateway error", "error_report"),
    ("tax calculation error", "error_report"),
    ("inventory calculation error", "error_report"),
    ("payroll calculation error", "error_report"),
    ("accounting balance error", "error_report"),
    ("stock valuation error", "error_report"),
    ("production calculation error", "error_report"),
    ("quality check error", "error_report"),
    ("maintenance scheduling error", "error_report"),
    ("project planning error", "error_report"),
    ("CRM integration error", "error_report"),
    ("HR system error", "error_report"),
    ("manufacturing system error", "error_report"),
    ("sales system error", "error_report"),
    ("purchase system error", "error_report"),
    ("inventory system error", "error_report"),
    ("accounting system error", "error_report"),
    ("reporting system error", "error_report"),
    ("analytics system error", "error_report"),
    ("dashboard error", "error_report"),
    ("mobile app error", "error_report"),
    ("web portal error", "error_report"),
    ("desktop app error", "error_report"),
    ("cloud sync error", "error_report"),

    # Data Search & Filters (50)
    ("search for invoice number", "search_query"),
    ("filter customers by city", "search_query"),
    ("find items by category", "search_query"),
    ("search employee by department", "search_query"),
    ("search customer by phone", "search_query"),
    ("filter invoices by date range", "search_query"),
    ("find product by SKU", "search_query"),
    ("search supplier by country", "search_query"),
    ("filter orders by status", "search_query"),
    ("search payment by reference", "search_query"),
    ("filter stock by warehouse", "search_query"),
    ("search batch by expiry date", "search_query"),
    ("filter serial numbers by product", "search_query"),
    ("search project by customer", "search_query"),
    ("filter tasks by assignee", "search_query"),
    ("search lead by source", "search_query"),
    ("filter opportunity by stage", "search_query"),
    ("search quotation by validity", "search_query"),
    ("filter sales order by delivery date", "search_query"),
    ("search purchase order by vendor", "search_query"),
    ("filter purchase invoice by due date", "search_query"),
    ("search material request by department", "search_query"),
    ("filter work order by production status", "search_query"),
    ("search BOM by finished product", "search_query"),
    ("filter job card by operation", "search_query"),
    ("search quality inspection by item", "search_query"),
    ("filter maintenance by equipment", "search_query"),
    ("search asset by location", "search_query"),
    ("filter depreciation by method", "search_query"),
    ("search journal entry by account", "search_query"),
    ("filter payment entry by party", "search_query"),
    ("search bank reconciliation by account", "search_query"),
    ("filter tax by category", "search_query"),
    ("search employee by designation", "search_query"),
    ("filter attendance by shift", "search_query"),
    ("search leave application by type", "search_query"),
    ("filter payroll by period", "search_query"),
    ("search expense claim by employee", "search_query"),
    ("filter loan by status", "search_query"),
    ("search advance by purpose", "search_query"),
    ("filter appraisal by rating", "search_query"),
    ("search recruitment by position", "search_query"),
    ("filter training by category", "search_query"),
    ("search support ticket by priority", "search_query"),
    ("filter warranty claim by product", "search_query"),
    ("search website order by customer", "search_query"),
    ("filter blog post by category", "search_query"),
    ("search product review by rating", "search_query"),
    ("filter website visitor by country", "search_query"),
    ("search SEO keyword by ranking", "search_query"),

    # Document Workflow (50)
    ("submit document for approval", "workflow_query"),
    ("check approval status", "workflow_query"),
    ("approve pending document", "workflow_query"),
    ("reject purchase request", "workflow_query"),
    ("submit expense report for approval", "workflow_query"),
    ("create purchase order approval workflow", "workflow_query"),
    ("update sales invoice approval process", "workflow_query"),
    ("create leave application workflow", "workflow_query"),
    ("update expense claim approval chain", "workflow_query"),
    ("create payment request workflow", "workflow_query"),
    ("update material request approval", "workflow_query"),
    ("create quality inspection workflow", "workflow_query"),
    ("update maintenance request approval", "workflow_query"),
    ("create asset purchase workflow", "workflow_query"),
    ("update project change request workflow", "workflow_query"),
    ("create recruitment approval workflow", "workflow_query"),
    ("update training request workflow", "workflow_query"),
    ("create budget approval workflow", "workflow_query"),
    ("update contract approval process", "workflow_query"),
    ("create vendor registration workflow", "workflow_query"),
    ("update customer credit limit approval", "workflow_query"),
    ("create price change approval workflow", "workflow_query"),
    ("update discount approval process", "workflow_query"),
    ("create return authorization workflow", "workflow_query"),
    ("update warranty claim approval", "workflow_query"),
    ("create refund approval workflow", "workflow_query"),
    ("update write-off approval process", "workflow_query"),
    ("create bad debt approval workflow", "workflow_query"),
    ("update inventory adjustment approval", "workflow_query"),
    ("create stock write-off workflow", "workflow_query"),
    ("update production change approval", "workflow_query"),
    ("create quality deviation workflow", "workflow_query"),
    ("update safety incident approval", "workflow_query"),
    ("create environmental compliance workflow", "workflow_query"),
    ("update regulatory approval process", "workflow_query"),
    ("create legal document workflow", "workflow_query"),
    ("update compliance certificate approval", "workflow_query"),
    ("create audit finding workflow", "workflow_query"),
    ("update corrective action approval", "workflow_query"),
    ("create risk assessment workflow", "workflow_query"),
    ("update business continuity approval", "workflow_query"),
    ("create disaster recovery workflow", "workflow_query"),
    ("update IT change approval process", "workflow_query"),
    ("create software update workflow", "workflow_query"),
    ("update hardware purchase workflow", "workflow_query"),
    ("create network change workflow", "workflow_query"),
    ("update security policy approval", "workflow_query"),
    ("create data access workflow", "workflow_query"),
    ("update privacy compliance workflow", "workflow_query"),
    ("create information security workflow", "workflow_query"),

    # Integration & API (50)
    ("sync with Shopify", "integration_query"),
    ("import data from Excel", "integration_query"),
    ("connect to payment gateway", "integration_query"),
    ("setup SMS notifications", "integration_query"),
    ("create multi-company transaction", "accounting_query"),
    ("update inter-company transfer", "inventory_query"),
    ("create API integration with CRM", "integration_query"),
    ("update ERP to accounting software sync", "integration_query"),
    ("create e-commerce platform integration", "integration_query"),
    ("update inventory management system integration", "integration_query"),
    ("create shipping carrier API integration", "integration_query"),
    ("update tax calculation service integration", "integration_query"),
    ("create bank statement import integration", "integration_query"),
    ("update payroll service integration", "integration_query"),
    ("create HRMS system integration", "integration_query"),
    ("update project management tool integration", "integration_query"),
    ("create manufacturing execution system integration", "integration_query"),
    ("update quality management system integration", "integration_query"),
    ("create maintenance management system integration", "integration_query"),
    ("update asset tracking system integration", "integration_query"),
    ("create customer support system integration", "integration_query"),
    ("update marketing automation integration", "integration_query"),
    ("create analytics platform integration", "integration_query"),
    ("update business intelligence tool integration", "integration_query"),
    ("create document management system integration", "integration_query"),
    ("update electronic signature integration", "integration_query"),
    ("create compliance monitoring integration", "integration_query"),
    ("update regulatory reporting integration", "integration_query"),
    ("create sustainability reporting integration", "integration_query"),
    ("update energy management system integration", "integration_query"),
    ("create waste management system integration", "integration_query"),
    ("update safety management system integration", "integration_query"),
    ("create environmental management system integration", "integration_query"),
    ("update quality management system integration", "integration_query"),
    ("create supply chain management integration", "integration_query"),
    ("update logistics management system integration", "integration_query"),
    ("create warehouse management system integration", "integration_query"),
    ("update transportation management system integration", "integration_query"),
    ("create fleet management system integration", "integration_query"),
    ("update facility management system integration", "integration_query"),
    ("create building management system integration", "integration_query"),
    ("update energy monitoring system integration", "integration_query"),
    ("create water management system integration", "integration_query"),
    ("update waste monitoring system integration", "integration_query"),
    ("create air quality monitoring integration", "integration_query"),
    ("update noise monitoring system integration", "integration_query"),
    ("create weather monitoring system integration", "integration_query"),
    ("update seismic monitoring system integration", "integration_query"),
    ("create flood monitoring system integration", "integration_query"),
    ("update fire monitoring system integration", "integration_query"),
]